language: python
python:
  - "3.6"
cache: pip
install:
  - pip3 install -r requirements.txt
script:
  - python3 -m pytest -v tests/test_BinaryTree.py 
  - python3 -m pytest -v tests/test_BST.py 
  - python3 -m pytest -v tests/test_AVLTree.py 
  - python3 -m pytest -v tests/test_Heap.py 
